### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by MainaMary**
The form user Interface

### CODE REVIEW

**Comment by MainaMary** [comment]
The form index.html

**Review by OnunwaGloryChimamanda — COMMENTED** [review]
The href  to the style sheet will change because the css file is now in a new folder.  Same applies to the js files.

**Review by OnunwaGloryChimamanda — COMMENTED** [review]
The script src also changes because the JS file is now in a new folder 
The main.js2 isn't linked in the script tag?

**Comment by OnunwaGloryChimamanda** [comment]
Closed

**Pull request closed without merging**
